---
name: Format indexer

on:
  workflow_call:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: indexer
      - name: install unzip
        run: apt update -y && apt upgrade -y && apt install zip -y
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Run formatting
        run: deno fmt --check indexer/
